#!/bin/sh
TCL_VERSIONS="8.5 8.6"
TCLSH=""

for VERSION in $TCL_VERSIONS; do
    TCL=`which tclsh$VERSION 2>/dev/null` && TCLSH=$TCL
done

if [ -z $TCLSH ]
then
    echo "You need tcl 8.5 or newer in order to run the Redis test"
    exit 1
fi

mkdir -p ../jenkins/report/integration

cd tests/qa/integration
LOG_LEVEL=""
TCLARGS=""
for ((i=1;i<=$#;i++))
do
    eval str=\${$i}
    case $str in
        --loglevel*)
            while ((i++<=$#))
            do
                eval str=\${$i}
                str=$(echo $str | tr [A-Z] [a-z])
                if [[ "debug notice verbose warning" =~ $str ]];then
                    LOG_LEVEL+=" "$str
                else
                    ((i--))
                    break
                fi
            done
            ;;
        *)
            TCLARGS+=" "$str
            ;;
    esac
done
LOG_LEVEL=$(echo $LOG_LEVEL)
if [[ $LOG_LEVEL == "" ]];then
    LOG_LEVEL="notice"
fi

for level in $LOG_LEVEL;do
    $TCLSH tests/test_helper.tcl $TCLARGS --loglevel $level
done
# $TCLSH tests/test_helper.tcl $*
